config/routes.rb
Rails.application.routes.draw do
  
  devise_for :users
  resources :follows, only: [:create, :destroy]
  #resources :likes, only: [:create]

  root to: "home#index"

  resources :users, only: [:show, :index, :edit, :update] do
    resources :posts do
      resources :comments
      resources :likes, only: [:create, :destroy]
    end
    resources :followers, only: :index
    resources :followings, only: :index
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
	belongs_to :post
	validates :comment, presence: true
end

app/models/follow.rb
class Follow < ApplicationRecord
	belongs_to :follower, class_name: "User", foreign_key: "follower_id"
	belongs_to :following, class_name: "User", foreign_key: "following_id"
end

app/models/like.rb
class Like < ApplicationRecord
	belongs_to :post
	belongs_to :user
end

app/models/post.rb
class Post < ApplicationRecord

	belongs_to :user
	has_many :comments
	has_many :likes

	include ImageUploader::Attachment(:image)

	validates :image, presence: true
	validates :description, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  has_many :posts
  has_many :likes

  has_many :follower_follows, foreign_key: :following_id, class_name: "Follow"
  has_many :followers, through: :follower_follows, source: :follower

  has_many :following_follows, foreign_key: :follower_id, class_name: "Follow"
  has_many :followings, through: :following_follows, source: :following  



  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :email, presence: true, uniqueness: true   
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	def after_sign_in_path_for(user)
		user_path(user)	
  	end

  	def after_sign_out_path_for(resource)
  		new_user_session_path
  	end
end
 

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :load_user, :load_post
  
  def new
    @comment = Comment.new
  end

  def edit
    @comment = @post.comments.find(params[:id])
  end

  def create
    @comment = Comment.new(comment_params)
    @comment.post = @post
      if @comment.save 
        redirect_to user_post_path(@user, @post)
      else  redirect_to user_post_path(@user, @post)
      end
  end

  def update
      @comment = @post.comments.find(params[:id])
      @comment.update(comment_params)
      
      redirect_to user_post_comment_path(@user, @post, @comment)
    
  end

  def destroy
    @comment = @post.comments.where(post_id: @post).take 
    @comment.destroy
    
    redirect_to user_post_path(@user, @post)     
  end

  private

    def load_post
      @post = Post.find(params[:post_id])
    end

    def comment_params
      params.require(:comment).permit(:user_name, :comment, :post_id)
    end

    def load_user
      @user = User.find(params[:user_id])
    end

end

app/controllers/followers_controller.rb
class FollowersController < ActionController::Base
	def index
		@user = User.find(params[:user_id])
		@followers = @user.followers
	end 
end

app/controllers/followings_controller.rb
class FollowingsController < ActionController::Base
	def index
		@user = User.find(params[:user_id])
		@followings = @user.followings
	end
end

app/controllers/follows_controller.rb
class FollowsController < ActionController::Base
	before_action :authenticate_user!

	def create
		if !current_user.followings.exists?(params[:following_id])
		#if !current_user.followings.include?(User.find(params[:following_id]))
			@user = User.find(params[:following_id])
			follower_user = current_user
			following_user = User.find(params[:following_id])

			Follow.create(follower: follower_user, following: following_user)

			redirect_to user_path(@user)
		end
	end

	def destroy
		if current_user.followings.exists?(params[:id])
		#if current_user.followings.include?(User.find(params[:id]))
			@follower_id = current_user.id
			@following_id = current_user.followings.find(params[:id]).id
			@follow = Follow.where(follower_id: @follower_id, following_id: @following_id).take
			@follow.destroy

			redirect_to user_path(params[:id])
		end
	end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_action :authenticate_user!

  def index 
    if current_user.followings.exists?
      @user = User.find(current_user.followings.pluck(:id))
      @posts = Post.where(user_id: current_user.followings.pluck(:id)).order(created_at: :desc)
    end
  end
end

app/controllers/likes_controller.rb
class LikesController < ActionController::Base
	before_action :authenticate_user!
	before_action :load_user, :load_post

	def create
		if !current_user.likes.exists?(post_id: @post)

			@like = current_user.likes.build(post: @post)

			if @like.save!
        		redirect_to user_post_path(@user, @post)
      		end
		end
	end

	def destroy
		if current_user.likes.exists?(post_id: @post)

			@like = current_user.likes.where(post_id: @post).take
			@like.destroy

			redirect_to user_post_path(@user, @post)
		end
	end

	private

	def load_user
		@user = User.find(params[:user_id])
	end
	def load_post
		@post = Post.find(params[:post_id])
	end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :load_user 

  def index
    @posts = @user.posts
  end
  
  def show 
    @post = @user.posts.find(params[:id]) 
  end

  def new
    @post = Post.new
  end

  def edit
    @post = @user.posts.find(params[:id])
  end

  def create
    @post = Post.new(post_params)
    @post.user = @user
      if @post.save
          redirect_to user_post_path(@user, @post), flash: {success: "Post was added"}
      else
          render action: :new
      end
  end 


  def update
    @post = @user.posts.find(params[:id])
    @post.update(post_params)
    
    redirect_to user_post_path(@user, @post)
  end 

  def destroy
    @post = @user.posts.find(params[:id])
    @post.destroy
    render action: :index
  end


  private

    def post_params
      params.require(:post).permit(:user_name, :user_id, :description, :image)
    end

    def load_user
      @user = User.find(params[:user_id])
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

	def index
		@users = User.all
	end

	def show
		@user = User.find(params[:id])
		@posts = current_user.posts.order(created_at: :desc)
	end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/followers/index.html.erb
<h1>Followers</h1> 

<ul>
	<% @followers.each do |follower| %>
		<li>
			<%= link_to(follower.email, user_path(follower)) %>
		</li>
	<% end %>
</ul>
<%= link_to("Back", user_path(@user), class:"btn btn-dark") %>

app/views/followings/index.html.erb
<h1>Followings</h1>

 
<ul>
	<% @followings.each do |following| %>
		<li>
			<%= link_to(following.email, user_path(following), class:"follow-user") %>
		</li>
	<% end %>
</ul>
<%= link_to("Back", user_path(@user), class:"btn btn-dark") %>

app/views/home/index.html.erb
<div class="posts">
  <% if !(@posts == nil) %>
    <% @posts.each do |post| %>
      <section class="post">
        <div class="username">
          <%= link_to(post.user_name, user_path(@user)) %>
        </div>  
        <%= image_tag post.image_url, class: 'main-image' %>
        <div class="description">
          <p><strong>
            <%= Like.where(post_id: post).count %> likes
          </strong></p><br>
          <%= post.description %>
        </div>
        <%= link_to 'Show', user_post_path(@user, post) %>
      </section>
    <% end %>
  <% end %> 
</div>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-dark bg-dark">
  <div class="container-fluid">
    <%= link_to "Instagram", user_path(current_user), class:"navbar-brand" %>
    <%= link_to "Users", users_path, class:"btn btn-dark" %>
    <%= link_to "Feed", root_path, class:"btn btn-dark" %>
    <%= link_to "Sign out", destroy_user_session_path, method: :delete, class:"btn btn-outline-light" %>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Instagram</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>



  <% if user_signed_in? %>
    <nav class="navbar navbar-light bg-light d-flex">
      <div class="container">
        <div class="logo">
          <a class="navbar-brand">
            <%= link_to "Instagram", user_path(current_user), class:"navbar-brand" %>
          </a>
        </div>
        <a>
            <%= link_to "Feed", root_path, class:"navbar-brand" %>
        </a>
        <a>
            <%= link_to "Users", users_path, class:"navbar-brand" %>
        </a>
        <a>
            <%= link_to "Sign out", destroy_user_session_path, method: :delete, class:"navbar-brand" %>
        </a>
      </div>
    </nav>

  <br/>
    <% else %>
      <br/><br/><br/>  
    <% end %> 


    <main class="container" style="min-height: 500px;">
      <%= yield %>
    </main>


  </body>
</html>

app/views/posts/_form.html.erb
<%= form_with(model: [@user, post], local: true) do |form| %>
  <% if post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
        <% post.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div> 
  <% end %>


  <div class="field">
    <%= form.hidden_field :image, value: post.cached_image_data %>
    <%= form.file_field :image %>
  </div>
  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description %>
  </div>  

<!--hidden fields --> 
  <div class="field">
    <%= form.text_field :user_id, id: :post_user_id, value: current_user.id, type: :hidden %>
  </div>
  <div class="field">
    <%= form.text_field :user_name, value: current_user.email, type: :hidden %>
  </div>
<!--hidden fields -->  

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/posts/edit.html.erb
<h1>Editing Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Show', user_post_path(@user, @post) %>
<%= link_to 'Back', user_posts_path(@user) %>

app/views/posts/index.html.erb
<div class="posts">
  <% if @posts.exists? %>
    <% @posts.each do |post| %>
      <section class="post">
        <div class="username">
          <%= link_to(post.user_name, user_path(@user)) %>
        </div>  
        <%= image_tag post.image_url, class: 'main-image' %>
        <div class="description">
          <p><strong>
            <%= Like.where(post_id: post).count %> likes
          </strong></p><br>
          <%= post.description %>
        </div>
        <%= link_to 'Show', user_post_path(@user, post) %>
        <% if @user.id == current_user.id %>
            <%= link_to 'Edit', edit_user_post_path(@user, post) %>
            <%= link_to 'Destroy', user_post_path(@user, post), method: :delete, data: { confirm: 'Are you sure?' } %>
          <% end %>
      </section>
    <% end %>
  <% end %> 
<%= link_to 'Back', user_path(@user) %>
</div> 

app/views/posts/new.html.erb
<h1>New Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Back', user_path(@user) %>

app/views/posts/show.html.erb
<div class="posts">
  <section class="post">
    <p>
      <strong>User name:</strong>
      <%= @post.user_name %> 
    </p>

    <p>
      <%= image_tag @post.image_url, class: 'main-image' %>
    </p>
    <p>
      <strong><%= Like.where(post_id: @post).count %> likes</strong>
    </p>
    <p>
      <strong>Description:</strong> 
      <%= @post.description %>
    </p>
    <!-- Likes  -->
<p> 
<% if current_user.present? && (current_user.likes.where(post_id: @post) == []) %>
    <%= link_to("Like", user_post_likes_path(post_id: @post.id), method: :post, class:"btn btn-dark") %>
<% elsif current_user.present? %>
  <%= link_to("Dislike", user_post_like_path(@user, @post), method: :delete, class:"btn btn-dark") %>
<% end %>
</p>
<!-- Likes  -->

<!-- Comments  -->
<% unless @post.comments == [] %>
  <h4>Comments:</h4>
<% end %>
<% @post.comments.each do |comment| %>
    <p><strong><%= comment.user_name %></strong>: 
      <%= comment.comment %>
      <% if current_user.email == comment.user_name %>
        <%= link_to 'Delete', user_post_comment_path(@user, @post, comment), method: :delete, data: { confirm: 'Are you sure?' } %>
      <% end %>
    </p>
<% end %>
<br/>
<!-- Comments  -->



<!-- Add a comment  -->
<h4>Add a comment:</h4>
<%= form_for([@user, @post, @post.comments.build]) do |f| %>
  <p>
    <%= f.hidden_field :user_name, value: current_user.email %>
  </p>

  <p>
    Comment:</br>
    <%= f.text_area :comment %> 
  </p>

  <p>
    <%= f.submit class:"btn btn-dark" %>  
  </p>
<% end %>

<!-- Add a comment  -->



<!-- Links  -->
<% if @user.id == current_user.id %>
<%= link_to 'Edit', edit_user_post_path(@user, @post) %> 
<% end %>
<%= link_to 'Back', user_posts_path(@user) %>
<!-- Links  --> 
  </section>
</div>

app/views/users/index.html.erb
<h1>Users</h1>

<table>
  <tbody>
    <% @users.each do |user| %>
      <% unless user.id == current_user.id %>      
        <tr class="user-all">
          <td class="user-all"><%= user.email %></td>
          <td class="user-all"><%= link_to 'Show', user_path(user) %></td>
        </tr>
      <% end %>
    <% end %>
  </tbody>
</table>

app/views/users/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider), method: :post %><br />
  <% end %>
<% end %>

app/views/users/show.html.erb
<div class="container">
<div class="col-md-8 basic-info">

    <div>
    		<h2>It's <%= @user.email  %></h2><br>
    		<p>
				<% if current_user.present? && current_user != @user && !current_user.followings.include?(User.find(@user.id)) %>
					<%= link_to("Follow", follows_path(following_id: @user.id), method: :post, class:"btn btn-dark")  %>
				<% elsif current_user.present? && current_user != @user %>
					<%= link_to("Unfollow", follow_path(@user), method: :delete, class:"btn btn-dark") %>
				<% end %>
			</p>
			
	</div>
	<p>
		<%= link_to("Followers", user_followers_path(@user), class:"btn btn-dark")  %>
		<%= link_to("Followings", user_followings_path(@user), class:"btn btn-dark")  %>
	</p>

	<%= link_to "Posts", user_posts_path(@user), class:"btn btn-dark" %>
	<br/><br/>
	<% if @user.id == current_user.id %>
		<%= link_to "Add post", new_user_post_path(current_user.id), class:"btn btn-dark" %>
	<% end %>
</div>
</div>